/**
 * THIS FILE IS AUTO-GENERATED by scripts/generate.ts
 * DO NOT EDIT MANUALLY. Re-run `pnpm generate` to regenerate.
 */

export const erc8004ReputationAbi = [
  {
    "type": "function",
    "name": "appendResponse",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "address"
      },
      {
        "name": "",
        "type": "uint64"
      },
      {
        "name": "",
        "type": "string"
      },
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "clients",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feedbackCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "feedbacks",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "address"
      },
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "value",
        "type": "int128"
      },
      {
        "name": "valueDecimals",
        "type": "uint8"
      },
      {
        "name": "tag1",
        "type": "string"
      },
      {
        "name": "tag2",
        "type": "string"
      },
      {
        "name": "isRevoked",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getClients",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getLastIndex",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "clientAddress",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getSummary",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "clientAddresses",
        "type": "address[]"
      },
      {
        "name": "",
        "type": "string"
      },
      {
        "name": "",
        "type": "string"
      }
    ],
    "outputs": [
      {
        "name": "count",
        "type": "uint64"
      },
      {
        "name": "summaryValue",
        "type": "int128"
      },
      {
        "name": "summaryValueDecimals",
        "type": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "giveFeedback",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "value",
        "type": "int128"
      },
      {
        "name": "valueDecimals",
        "type": "uint8"
      },
      {
        "name": "tag1",
        "type": "string"
      },
      {
        "name": "tag2",
        "type": "string"
      },
      {
        "name": "",
        "type": "string"
      },
      {
        "name": "",
        "type": "string"
      },
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "lastIndexes",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "readFeedback",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "clientAddress",
        "type": "address"
      },
      {
        "name": "feedbackIndex",
        "type": "uint64"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "int128"
      },
      {
        "name": "",
        "type": "uint8"
      },
      {
        "name": "",
        "type": "string"
      },
      {
        "name": "",
        "type": "string"
      },
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "revokeFeedback",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "feedbackIndex",
        "type": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "FeedbackGiven",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "client",
        "type": "address",
        "indexed": false
      },
      {
        "name": "value",
        "type": "int128",
        "indexed": false
      },
      {
        "name": "tag1",
        "type": "string",
        "indexed": false
      },
      {
        "name": "tag2",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  }
] as const;
