/**
 * THIS FILE IS AUTO-GENERATED by scripts/generate.ts
 * DO NOT EDIT MANUALLY. Re-run `pnpm generate` to regenerate.
 */

export const erc8004ValidationAbi = [
  {
    "type": "function",
    "name": "agentValidations",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAgentValidations",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getSummary",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "address[]"
      },
      {
        "name": "",
        "type": "string"
      }
    ],
    "outputs": [
      {
        "name": "count",
        "type": "uint64"
      },
      {
        "name": "averageResponse",
        "type": "uint8"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "getValidationStatus",
    "inputs": [
      {
        "name": "requestHash",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "validatorAddress",
        "type": "address"
      },
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "response",
        "type": "uint8"
      },
      {
        "name": "responseHash",
        "type": "bytes32"
      },
      {
        "name": "tag",
        "type": "string"
      },
      {
        "name": "lastUpdate",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getValidatorRequests",
    "inputs": [
      {
        "name": "validatorAddress",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "statuses",
    "inputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "validatorAddress",
        "type": "address"
      },
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "response",
        "type": "uint8"
      },
      {
        "name": "responseHash",
        "type": "bytes32"
      },
      {
        "name": "tag",
        "type": "string"
      },
      {
        "name": "lastUpdate",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "submitResponse",
    "inputs": [
      {
        "name": "requestHash",
        "type": "bytes32"
      },
      {
        "name": "score",
        "type": "uint8"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "validationRequest",
    "inputs": [
      {
        "name": "validatorAddress",
        "type": "address"
      },
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "requestURI",
        "type": "string"
      },
      {
        "name": "requestHash",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "validationResponse",
    "inputs": [
      {
        "name": "requestHash",
        "type": "bytes32"
      },
      {
        "name": "response",
        "type": "uint8"
      },
      {
        "name": "",
        "type": "string"
      },
      {
        "name": "responseHash",
        "type": "bytes32"
      },
      {
        "name": "tag",
        "type": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "validatorRequests",
    "inputs": [
      {
        "name": "",
        "type": "address"
      },
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "ValidationRequestEmitted",
    "inputs": [
      {
        "name": "validatorAddress",
        "type": "address",
        "indexed": true
      },
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "requestURI",
        "type": "string",
        "indexed": false
      },
      {
        "name": "requestHash",
        "type": "bytes32",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ValidationResponseEmitted",
    "inputs": [
      {
        "name": "validatorAddress",
        "type": "address",
        "indexed": true
      },
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "requestHash",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "response",
        "type": "uint8",
        "indexed": false
      }
    ],
    "anonymous": false
  }
] as const;
