/**
 * THIS FILE IS AUTO-GENERATED by scripts/generate.ts
 * DO NOT EDIT MANUALLY. Re-run `pnpm generate` to regenerate.
 */

export const aegisDisputeAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_escrow",
        "type": "address"
      },
      {
        "name": "_usdc",
        "type": "address"
      },
      {
        "name": "_treasury",
        "type": "address"
      },
      {
        "name": "_owner",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "activeArbitrators",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "arbitratorStakes",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "arbitratorStats",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "totalResolutions",
        "type": "uint256"
      },
      {
        "name": "successfulResolutions",
        "type": "uint256"
      },
      {
        "name": "totalFeesEarned",
        "type": "uint256"
      },
      {
        "name": "lastActiveAt",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "assignArbitrator",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "disputeBondAmount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "disputeTTLSeconds",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "disputes",
    "inputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      },
      {
        "name": "initiator",
        "type": "address"
      },
      {
        "name": "respondent",
        "type": "address"
      },
      {
        "name": "initiatorEvidenceURI",
        "type": "string"
      },
      {
        "name": "initiatorEvidenceHash",
        "type": "bytes32"
      },
      {
        "name": "respondentEvidenceURI",
        "type": "string"
      },
      {
        "name": "respondentEvidenceHash",
        "type": "bytes32"
      },
      {
        "name": "respondentSubmitted",
        "type": "bool"
      },
      {
        "name": "arbitrator",
        "type": "address"
      },
      {
        "name": "ruling",
        "type": "uint8"
      },
      {
        "name": "rationaleURI",
        "type": "string"
      },
      {
        "name": "rationaleHash",
        "type": "bytes32"
      },
      {
        "name": "createdAt",
        "type": "uint256"
      },
      {
        "name": "evidenceDeadline",
        "type": "uint256"
      },
      {
        "name": "resolutionDeadline",
        "type": "uint256"
      },
      {
        "name": "initiatorBond",
        "type": "uint256"
      },
      {
        "name": "resolved",
        "type": "bool"
      },
      {
        "name": "method",
        "type": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "escrow",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "evidenceWindowSeconds",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getActiveArbitratorCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getArbitratorStats",
    "inputs": [
      {
        "name": "arbitrator",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "totalResolutions",
            "type": "uint256"
          },
          {
            "name": "successfulResolutions",
            "type": "uint256"
          },
          {
            "name": "totalFeesEarned",
            "type": "uint256"
          },
          {
            "name": "lastActiveAt",
            "type": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getDispute",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "jobId",
            "type": "bytes32"
          },
          {
            "name": "initiator",
            "type": "address"
          },
          {
            "name": "respondent",
            "type": "address"
          },
          {
            "name": "initiatorEvidenceURI",
            "type": "string"
          },
          {
            "name": "initiatorEvidenceHash",
            "type": "bytes32"
          },
          {
            "name": "respondentEvidenceURI",
            "type": "string"
          },
          {
            "name": "respondentEvidenceHash",
            "type": "bytes32"
          },
          {
            "name": "respondentSubmitted",
            "type": "bool"
          },
          {
            "name": "arbitrator",
            "type": "address"
          },
          {
            "name": "ruling",
            "type": "uint8"
          },
          {
            "name": "rationaleURI",
            "type": "string"
          },
          {
            "name": "rationaleHash",
            "type": "bytes32"
          },
          {
            "name": "createdAt",
            "type": "uint256"
          },
          {
            "name": "evidenceDeadline",
            "type": "uint256"
          },
          {
            "name": "resolutionDeadline",
            "type": "uint256"
          },
          {
            "name": "initiatorBond",
            "type": "uint256"
          },
          {
            "name": "resolved",
            "type": "bool"
          },
          {
            "name": "method",
            "type": "uint8"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getDisputeForJob",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initiateDispute",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      },
      {
        "name": "initiator",
        "type": "address"
      },
      {
        "name": "evidenceURI",
        "type": "string"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isArbitrator",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "jobToDispute",
    "inputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minArbitratorStake",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "processReValidation",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32"
      },
      {
        "name": "reValidationHash",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "requestReValidation",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32"
      },
      {
        "name": "newValidatorAddress",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "resolveByArbitrator",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32"
      },
      {
        "name": "clientPercent",
        "type": "uint8"
      },
      {
        "name": "rationaleURI",
        "type": "string"
      },
      {
        "name": "rationaleHash",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "resolveByTimeout",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDisputeBondAmount",
    "inputs": [
      {
        "name": "_amount",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDisputeTTLSeconds",
    "inputs": [
      {
        "name": "_seconds",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setEvidenceWindowSeconds",
    "inputs": [
      {
        "name": "_seconds",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMinArbitratorStake",
    "inputs": [
      {
        "name": "_amount",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setTreasury",
    "inputs": [
      {
        "name": "_treasury",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setValidationTolerance",
    "inputs": [
      {
        "name": "_tolerance",
        "type": "uint8"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "stakeAsArbitrator",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitEvidence",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32"
      },
      {
        "name": "evidenceURI",
        "type": "string"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "totalDisputes",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "treasury",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "unstakeArbitrator",
    "inputs": [
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "usdc",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "validationTolerance",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "ArbitratorAssigned",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "arbitrator",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ArbitratorSlashed",
    "inputs": [
      {
        "name": "arbitrator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ArbitratorStaked",
    "inputs": [
      {
        "name": "arbitrator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ArbitratorUnstaked",
    "inputs": [
      {
        "name": "arbitrator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BondForfeited",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "from",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "BondReturned",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DisputeInitiated",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "initiator",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DisputeResolved",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "clientPercent",
        "type": "uint8",
        "indexed": false
      },
      {
        "name": "method",
        "type": "uint8",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EvidenceSubmitted",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "submitter",
        "type": "address",
        "indexed": true
      },
      {
        "name": "evidenceURI",
        "type": "string",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReValidationRequested",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "newValidationHash",
        "type": "bytes32",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "DisputeAlreadyExists",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "DisputeAlreadyResolved",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "DisputeNotFound",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "EvidenceWindowClosed",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidRuling",
    "inputs": [
      {
        "name": "ruling",
        "type": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidValidator",
    "inputs": [
      {
        "name": "validator",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotArbitrator",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32"
      },
      {
        "name": "caller",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotAuthorized",
    "inputs": [
      {
        "name": "caller",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotJobParty",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      },
      {
        "name": "caller",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ResolutionDeadlineNotPassed",
    "inputs": [
      {
        "name": "disputeId",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ValidationNotComplete",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
