/**
 * THIS FILE IS AUTO-GENERATED by scripts/generate.ts
 * DO NOT EDIT MANUALLY. Re-run `pnpm generate` to regenerate.
 */

export const aegisJobFactoryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_escrow",
        "type": "address"
      },
      {
        "name": "_owner",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createJobFromTemplate",
    "inputs": [
      {
        "name": "templateId",
        "type": "uint256"
      },
      {
        "name": "clientAgentId",
        "type": "uint256"
      },
      {
        "name": "providerAgentId",
        "type": "uint256"
      },
      {
        "name": "jobSpecHash",
        "type": "bytes32"
      },
      {
        "name": "jobSpecURI",
        "type": "string"
      },
      {
        "name": "amount",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createTemplate",
    "inputs": [
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "defaultValidator",
        "type": "address"
      },
      {
        "name": "defaultTimeout",
        "type": "uint256"
      },
      {
        "name": "feeBps",
        "type": "uint256"
      },
      {
        "name": "minValidation",
        "type": "uint8"
      },
      {
        "name": "defaultDisputeSplit",
        "type": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "templateId",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "deactivateTemplate",
    "inputs": [
      {
        "name": "templateId",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "escrow",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getTemplate",
    "inputs": [
      {
        "name": "templateId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "name",
            "type": "string"
          },
          {
            "name": "defaultValidator",
            "type": "address"
          },
          {
            "name": "defaultTimeout",
            "type": "uint256"
          },
          {
            "name": "feeBps",
            "type": "uint256"
          },
          {
            "name": "minValidation",
            "type": "uint8"
          },
          {
            "name": "defaultDisputeSplit",
            "type": "uint8"
          },
          {
            "name": "active",
            "type": "bool"
          },
          {
            "name": "creator",
            "type": "address"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isTemplateActive",
    "inputs": [
      {
        "name": "templateId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "openTemplateCreation",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setOpenTemplateCreation",
    "inputs": [
      {
        "name": "_open",
        "type": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "templateCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "templates",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "defaultValidator",
        "type": "address"
      },
      {
        "name": "defaultTimeout",
        "type": "uint256"
      },
      {
        "name": "feeBps",
        "type": "uint256"
      },
      {
        "name": "minValidation",
        "type": "uint8"
      },
      {
        "name": "defaultDisputeSplit",
        "type": "uint8"
      },
      {
        "name": "active",
        "type": "bool"
      },
      {
        "name": "creator",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "updateTemplateValidator",
    "inputs": [
      {
        "name": "templateId",
        "type": "uint256"
      },
      {
        "name": "newValidator",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "JobCreatedFromTemplate",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "templateId",
        "type": "uint256",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TemplateCreated",
    "inputs": [
      {
        "name": "templateId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "name",
        "type": "string",
        "indexed": false
      },
      {
        "name": "creator",
        "type": "address",
        "indexed": true
      },
      {
        "name": "defaultValidator",
        "type": "address",
        "indexed": false
      },
      {
        "name": "defaultTimeout",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "minValidation",
        "type": "uint8",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TemplateDeactivated",
    "inputs": [
      {
        "name": "templateId",
        "type": "uint256",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TemplateUpdated",
    "inputs": [
      {
        "name": "templateId",
        "type": "uint256",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "NotAuthorized",
    "inputs": [
      {
        "name": "caller",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TemplateNotActive",
    "inputs": [
      {
        "name": "templateId",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TemplateNotFound",
    "inputs": [
      {
        "name": "templateId",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
