/**
 * THIS FILE IS AUTO-GENERATED by scripts/generate.ts
 * DO NOT EDIT MANUALLY. Re-run `pnpm generate` to regenerate.
 */

export const aegisEscrowAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_identityRegistry",
        "type": "address"
      },
      {
        "name": "_reputationRegistry",
        "type": "address"
      },
      {
        "name": "_validationRegistry",
        "type": "address"
      },
      {
        "name": "_usdc",
        "type": "address"
      },
      {
        "name": "_treasury",
        "type": "address"
      },
      {
        "name": "_owner",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "agentJobs",
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      },
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "authorizedCallers",
    "inputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claimTimeout",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "confirmDelivery",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createJob",
    "inputs": [
      {
        "name": "clientAgentId",
        "type": "uint256"
      },
      {
        "name": "providerAgentId",
        "type": "uint256"
      },
      {
        "name": "jobSpecHash",
        "type": "bytes32"
      },
      {
        "name": "jobSpecURI",
        "type": "string"
      },
      {
        "name": "validatorAddress",
        "type": "address"
      },
      {
        "name": "deadline",
        "type": "uint256"
      },
      {
        "name": "amount",
        "type": "uint256"
      },
      {
        "name": "validationThreshold",
        "type": "uint8"
      }
    ],
    "outputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "defaultValidationThreshold",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "disputeContract",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "disputeWindowSeconds",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAgentJobCount",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAgentJobIds",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getJob",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "components": [
          {
            "name": "clientAgentId",
            "type": "uint256"
          },
          {
            "name": "providerAgentId",
            "type": "uint256"
          },
          {
            "name": "clientAddress",
            "type": "address"
          },
          {
            "name": "providerWallet",
            "type": "address"
          },
          {
            "name": "jobSpecHash",
            "type": "bytes32"
          },
          {
            "name": "jobSpecURI",
            "type": "string"
          },
          {
            "name": "templateId",
            "type": "uint256"
          },
          {
            "name": "validatorAddress",
            "type": "address"
          },
          {
            "name": "validationRequestHash",
            "type": "bytes32"
          },
          {
            "name": "validationScore",
            "type": "uint8"
          },
          {
            "name": "validationThreshold",
            "type": "uint8"
          },
          {
            "name": "amount",
            "type": "uint256"
          },
          {
            "name": "protocolFeeBps",
            "type": "uint256"
          },
          {
            "name": "createdAt",
            "type": "uint256"
          },
          {
            "name": "deadline",
            "type": "uint256"
          },
          {
            "name": "deliveredAt",
            "type": "uint256"
          },
          {
            "name": "settledAt",
            "type": "uint256"
          },
          {
            "name": "disputeWindowEnd",
            "type": "uint256"
          },
          {
            "name": "deliverableHash",
            "type": "bytes32"
          },
          {
            "name": "deliverableURI",
            "type": "string"
          },
          {
            "name": "state",
            "type": "uint8"
          },
          {
            "name": "resolution",
            "type": "uint8"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "identityRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "jobExists",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "jobs",
    "inputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "clientAgentId",
        "type": "uint256"
      },
      {
        "name": "providerAgentId",
        "type": "uint256"
      },
      {
        "name": "clientAddress",
        "type": "address"
      },
      {
        "name": "providerWallet",
        "type": "address"
      },
      {
        "name": "jobSpecHash",
        "type": "bytes32"
      },
      {
        "name": "jobSpecURI",
        "type": "string"
      },
      {
        "name": "templateId",
        "type": "uint256"
      },
      {
        "name": "validatorAddress",
        "type": "address"
      },
      {
        "name": "validationRequestHash",
        "type": "bytes32"
      },
      {
        "name": "validationScore",
        "type": "uint8"
      },
      {
        "name": "validationThreshold",
        "type": "uint8"
      },
      {
        "name": "amount",
        "type": "uint256"
      },
      {
        "name": "protocolFeeBps",
        "type": "uint256"
      },
      {
        "name": "createdAt",
        "type": "uint256"
      },
      {
        "name": "deadline",
        "type": "uint256"
      },
      {
        "name": "deliveredAt",
        "type": "uint256"
      },
      {
        "name": "settledAt",
        "type": "uint256"
      },
      {
        "name": "disputeWindowEnd",
        "type": "uint256"
      },
      {
        "name": "deliverableHash",
        "type": "bytes32"
      },
      {
        "name": "deliverableURI",
        "type": "string"
      },
      {
        "name": "state",
        "type": "uint8"
      },
      {
        "name": "resolution",
        "type": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxDeadlineDuration",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minEscrowAmount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pause",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "paused",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "processValidation",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "protocolFeeBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "raiseDispute",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      },
      {
        "name": "evidenceURI",
        "type": "string"
      },
      {
        "name": "evidenceHash",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "reputationRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "resolveDispute",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      },
      {
        "name": "clientPercent",
        "type": "uint8"
      },
      {
        "name": "method",
        "type": "uint8"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setAuthorizedCaller",
    "inputs": [
      {
        "name": "caller",
        "type": "address"
      },
      {
        "name": "authorized",
        "type": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDefaultValidationThreshold",
    "inputs": [
      {
        "name": "_threshold",
        "type": "uint8"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDisputeContract",
    "inputs": [
      {
        "name": "_disputeContract",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDisputeWindow",
    "inputs": [
      {
        "name": "_seconds",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMaxDeadlineDuration",
    "inputs": [
      {
        "name": "_duration",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMinEscrowAmount",
    "inputs": [
      {
        "name": "_amount",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setProtocolFee",
    "inputs": [
      {
        "name": "_feeBps",
        "type": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setTreasury",
    "inputs": [
      {
        "name": "_treasury",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "settleAfterDisputeWindow",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitDeliverable",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      },
      {
        "name": "deliverableURI",
        "type": "string"
      },
      {
        "name": "deliverableHash",
        "type": "bytes32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "totalJobsCreated",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "totalVolumeSettled",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "treasury",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "unpause",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "usdc",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "validationRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "validationToJob",
    "inputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AuthorizedCallerUpdated",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "indexed": true
      },
      {
        "name": "authorized",
        "type": "bool",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ClientConfirmed",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DeliverableSubmitted",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "deliverableURI",
        "type": "string",
        "indexed": false
      },
      {
        "name": "deliverableHash",
        "type": "bytes32",
        "indexed": false
      },
      {
        "name": "validationRequestHash",
        "type": "bytes32",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DisputeContractUpdated",
    "inputs": [
      {
        "name": "oldDispute",
        "type": "address",
        "indexed": false
      },
      {
        "name": "newDispute",
        "type": "address",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DisputeRaised",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "initiator",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DisputeWindowStarted",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "windowEnd",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DisputeWindowUpdated",
    "inputs": [
      {
        "name": "oldWindow",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "newWindow",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "FeedbackSubmitted",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "agentId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "value",
        "type": "int128",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "JobCancelled",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "JobCreated",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "clientAgentId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "providerAgentId",
        "type": "uint256",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "validatorAddress",
        "type": "address",
        "indexed": false
      },
      {
        "name": "deadline",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "JobFunded",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "JobRefunded",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "clientAddress",
        "type": "address",
        "indexed": true
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "JobSettled",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "providerWallet",
        "type": "address",
        "indexed": true
      },
      {
        "name": "providerAmount",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "protocolFee",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Paused",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProtocolFeeUpdated",
    "inputs": [
      {
        "name": "oldFee",
        "type": "uint256",
        "indexed": false
      },
      {
        "name": "newFee",
        "type": "uint256",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TreasuryUpdated",
    "inputs": [
      {
        "name": "oldTreasury",
        "type": "address",
        "indexed": false
      },
      {
        "name": "newTreasury",
        "type": "address",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Unpaused",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ValidationReceived",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32",
        "indexed": true
      },
      {
        "name": "score",
        "type": "uint8",
        "indexed": false
      },
      {
        "name": "passedThreshold",
        "type": "bool",
        "indexed": false
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AgentWalletNotSet",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "DeadlineNotPassed",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      },
      {
        "name": "deadline",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "DeadlinePassed",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      },
      {
        "name": "deadline",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "DisputeWindowClosed",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "DisputeWindowOpen",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "EnforcedPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExpectedPause",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InsufficientAmount",
    "inputs": [
      {
        "name": "provided",
        "type": "uint256"
      },
      {
        "name": "required",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidDeadline",
    "inputs": [
      {
        "name": "deadline",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidJobState",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      },
      {
        "name": "current",
        "type": "uint8"
      },
      {
        "name": "expected",
        "type": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidRuling",
    "inputs": [
      {
        "name": "ruling",
        "type": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidThreshold",
    "inputs": [
      {
        "name": "threshold",
        "type": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidValidator",
    "inputs": [
      {
        "name": "validator",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "JobNotFound",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotAgentOwner",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      },
      {
        "name": "caller",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotAuthorized",
    "inputs": [
      {
        "name": "caller",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotJobParty",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      },
      {
        "name": "caller",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SameAgent",
    "inputs": [
      {
        "name": "agentId",
        "type": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "ValidationNotComplete",
    "inputs": [
      {
        "name": "jobId",
        "type": "bytes32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
