/**
 * ABI Generation Script
 *
 * Reads Foundry compilation artifacts from the `out/` directory and generates
 * TypeScript files with `as const` assertions for full abitype inference.
 *
 * Usage: tsx scripts/generate.ts
 *
 * DO NOT EDIT THE GENERATED OUTPUT FILES MANUALLY.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/** Root of the Foundry project (worktree root, four levels above scripts dir) */
const FOUNDRY_OUT = resolve(__dirname, "../../../../out");

/** Output source directory */
const SRC_DIR = resolve(__dirname, "../src");

/** Header prepended to every generated file */
const FILE_HEADER = `/**
 * THIS FILE IS AUTO-GENERATED by scripts/generate.ts
 * DO NOT EDIT MANUALLY. Re-run \`pnpm generate\` to regenerate.
 */\n\n`;

/**
 * Mapping from Foundry artifact path (relative to out/) to the generated
 * TypeScript output. Each entry defines:
 *  - artifactPath: path inside out/ to the JSON artifact
 *  - outputPath:   path inside src/ for the generated .ts file
 *  - exportName:   the exported const name (camelCase + "Abi" suffix)
 */
interface AbiMapping {
  artifactPath: string;
  outputPath: string;
  exportName: string;
}

const ABI_MAPPINGS: AbiMapping[] = [
  // Core AEGIS contracts
  {
    artifactPath: "AegisEscrow.sol/AegisEscrow.json",
    outputPath: "AegisEscrow.ts",
    exportName: "aegisEscrowAbi",
  },
  {
    artifactPath: "AegisDispute.sol/AegisDispute.json",
    outputPath: "AegisDispute.ts",
    exportName: "aegisDisputeAbi",
  },
  {
    artifactPath: "AegisTreasury.sol/AegisTreasury.json",
    outputPath: "AegisTreasury.ts",
    exportName: "aegisTreasuryAbi",
  },
  {
    artifactPath: "AegisJobFactory.sol/AegisJobFactory.json",
    outputPath: "AegisJobFactory.ts",
    exportName: "aegisJobFactoryAbi",
  },
  // ERC-8004 registry ABIs (from mock contracts that implement the interfaces)
  {
    artifactPath: "Mocks.sol/MockIdentityRegistry.json",
    outputPath: "erc8004/Identity.ts",
    exportName: "erc8004IdentityAbi",
  },
  {
    artifactPath: "Mocks.sol/MockReputationRegistry.json",
    outputPath: "erc8004/Reputation.ts",
    exportName: "erc8004ReputationAbi",
  },
  {
    artifactPath: "Mocks.sol/MockValidationRegistry.json",
    outputPath: "erc8004/Validation.ts",
    exportName: "erc8004ValidationAbi",
  },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Reads a Foundry artifact JSON file and returns the `abi` array.
 * Strips the `internalType` field from each ABI entry — it is Solidity-specific
 * metadata not needed by abitype or viem.
 */
function extractAbi(artifactPath: string): unknown[] {
  const fullPath = join(FOUNDRY_OUT, artifactPath);

  if (!existsSync(fullPath)) {
    throw new Error(`Foundry artifact not found: ${fullPath}`);
  }

  const artifact = JSON.parse(readFileSync(fullPath, "utf-8"));

  if (!Array.isArray(artifact.abi)) {
    throw new Error(`Invalid artifact (no abi array): ${fullPath}`);
  }

  return stripInternalType(artifact.abi);
}

/**
 * Recursively removes `internalType` from ABI objects. This keeps the
 * generated TypeScript smaller and avoids Solidity-specific noise.
 */
function stripInternalType(obj: unknown): unknown {
  if (Array.isArray(obj)) {
    return obj.map(stripInternalType);
  }
  if (obj !== null && typeof obj === "object") {
    const result: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(obj as Record<string, unknown>)) {
      if (key === "internalType") continue;
      result[key] = stripInternalType(value);
    }
    return result;
  }
  return obj;
}

/**
 * Serialises the ABI array to a nicely formatted TypeScript `as const` export.
 */
function formatAbiModule(exportName: string, abi: unknown[]): string {
  const abiJson = JSON.stringify(abi, null, 2);
  return `${FILE_HEADER}export const ${exportName} = ${abiJson} as const;\n`;
}

// ---------------------------------------------------------------------------
// Barrel export generation
// ---------------------------------------------------------------------------

function generateBarrelExport(mappings: AbiMapping[]): string {
  const lines = mappings.map((m) => {
    // Convert outputPath to a relative import (strip .ts extension)
    const importPath = "./" + m.outputPath.replace(/\.ts$/, "");
    return `export { ${m.exportName} } from "${importPath}";`;
  });

  return `${FILE_HEADER}${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main(): void {
  console.log(`Reading Foundry artifacts from: ${FOUNDRY_OUT}`);
  console.log(`Writing TypeScript ABIs to:     ${SRC_DIR}\n`);

  if (!existsSync(FOUNDRY_OUT)) {
    console.error(
      `ERROR: Foundry out/ directory not found at ${FOUNDRY_OUT}.\n` +
        `Run \`forge build\` first to compile the contracts.`
    );
    process.exit(1);
  }

  let generated = 0;

  for (const mapping of ABI_MAPPINGS) {
    const abi = extractAbi(mapping.artifactPath);
    const content = formatAbiModule(mapping.exportName, abi);
    const outPath = join(SRC_DIR, mapping.outputPath);

    // Ensure subdirectories exist (e.g., src/erc8004/)
    mkdirSync(dirname(outPath), { recursive: true });

    writeFileSync(outPath, content, "utf-8");
    console.log(`  [ok] ${mapping.outputPath} (${abi.length} entries) → ${mapping.exportName}`);
    generated++;
  }

  // Generate barrel export
  const barrelContent = generateBarrelExport(ABI_MAPPINGS);
  const barrelPath = join(SRC_DIR, "index.ts");
  writeFileSync(barrelPath, barrelContent, "utf-8");
  console.log(`  [ok] index.ts (barrel export)`);

  console.log(`\nDone. Generated ${generated} ABI files + barrel export.\n`);
}

main();
